language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

script:
  - cl -e '(ql:quickload :meniere)'

notifications:
  email:
    - azimut.github@protonmail.com
