language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash
  - sudo apt-get -qq install libsndfile fluidsynth
  - git clone https://github.com/titola/incudine.git quicklisp/local-projects/incudine
  - git clone https://github.com/ormf/cm.git quicklisp/local-projects/cm

script:
  - cl -e '(ql:quickload :meniere)'

notifications:
  email:
    - azimut.github@protonmail.com
